#!/usr/bin/env bash
# Generates RSA-2048 and RSA-4096 test vectors for Solidity benchmarks.
# Outputs: modulus (n), public exponent (e), message, and signature as 0x-prefixed hex.
# Requires: openssl, xxd

set -euo pipefail

MESSAGE="hello"

generate_vectors() {
    local bits="$1"
    local key_file
    key_file=$(mktemp)
    trap "rm -f '$key_file'" RETURN

    # Generate RSA key
    openssl genpkey -algorithm RSA -pkeyopt "rsa_keygen_bits:${bits}" -out "$key_file" 2>/dev/null

    # Extract modulus (n) as lowercase hex
    local modulus
    modulus=$(openssl rsa -in "$key_file" -noout -modulus 2>/dev/null \
        | sed 's/Modulus=//' \
        | tr '[:upper:]' '[:lower:]')

    # Extract public exponent as hex
    local exponent
    exponent=$(openssl pkey -in "$key_file" -text -noout 2>/dev/null \
        | grep "Exponent:" \
        | grep -o '0x[0-9a-fA-F]*')

    # Sign the message with PKCS#1 v1.5 SHA-256
    local sig_file
    sig_file=$(mktemp)
    printf '%s' "$MESSAGE" | openssl dgst -sha256 -sign "$key_file" -out "$sig_file"
    local signature
    signature=$(xxd -p "$sig_file" | tr -d '\n')
    rm -f "$sig_file"

    # Message as hex
    local msg_hex
    msg_hex=$(printf '%s' "$MESSAGE" | xxd -p | tr -d '\n')

    # Normalize exponent: remove 0x prefix, ensure even-length, lowercase
    local exp_hex
    exp_hex=$(printf '%s' "$exponent" | sed 's/0x//' | tr '[:upper:]' '[:lower:]')
    # Pad to even length if needed
    if (( ${#exp_hex} % 2 != 0 )); then
        exp_hex="0${exp_hex}"
    fi

    echo "// RSA-${bits} Test Vector"
    echo "// Message: \"${MESSAGE}\""
    echo "bytes constant MSG_${bits} = hex\"${msg_hex}\";"
    echo "bytes constant N_${bits} = hex\"${modulus}\";"
    echo "bytes constant E_${bits} = hex\"${exp_hex}\";"
    echo "bytes constant SIG_${bits} = hex\"${signature}\";"
    echo ""
}

echo "// Auto-generated by scripts/generate_test_vectors.sh"
echo "// Do not edit manually. Re-run the script to regenerate."
echo ""
generate_vectors 2048
generate_vectors 4096
